const MY_DISCOUNTS_LIST = 'MY-DISCOUNTS-LIST';
const FEATURED_PRODUCTS_LIST = 'FEATURED-PRODUCTS-LIST';
const PRODUCT_DETAIL = 'PRODUCT-DETAIL';

const QueryConstants = {
  MY_DISCOUNTS_LIST,
  FEATURED_PRODUCTS_LIST,
  PRODUCT_DETAIL,
};

export default QueryConstants;
