const MY_DISCOUNTS_LIST = 'MY-DISCOUNTS-LIST';
const FEATURED_PRODUCTS_LIST = 'FEATURED-PRODUCTS-LIST';
const PRODUCT_DETAIL = 'PRODUCT-DETAIL';
const USER_DETAIL = 'USER-DETAIL';
const COMPANY_LOCATION = 'COMPANY-LOCATION';
const REGISTER_PRODUCTS_LIST = 'REGISTER-PRODUCTS-LIST';

const QueryConstants = {
  MY_DISCOUNTS_LIST,
  FEATURED_PRODUCTS_LIST,
  PRODUCT_DETAIL,
  USER_DETAIL,
  COMPANY_LOCATION,
  REGISTER_PRODUCTS_LIST,
};

export default QueryConstants;
